In [40]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [4]:
iris = load_iris(as_frame=True)

In [19]:
datax = iris.data

In [20]:
datay = iris.target

In [21]:
datax.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [34]:
datay.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [22]:
X = datax[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']].values

In [23]:
Y = datay.values

In [24]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [36]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 4)

In [39]:
SVM = SVC().fit(x_train,y_train)
yhat = SVM.predict(x_test)

In [41]:
print("Confusion Matrix")
print(metrics.confusion_matrix(y_test,yhat))

Confusion Matrix
[[18  0  0]
 [ 0  7  1]
 [ 0  0 12]]


In [42]:
print(metrics.classification_report(y_test,yhat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      0.88      0.93         8
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.96      0.96        38
weighted avg       0.98      0.97      0.97        38



In [44]:
print("Độ chính xác của SVM: ",metrics.accuracy_score(y_test,yhat))

Độ chính xác của SVM:  0.9736842105263158
